# Generated by Django 5.0 on 2023-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='image',
            field=models.URLField(default=None),
        ),
    ]
