# Generated by Django 5.0 on 2023-12-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0003_alter_headlines_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headlines',
            old_name='image',
            new_name='image_urls',
        ),
    ]
