# Generated by Django 5.0 on 2023-12-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0004_rename_image_headlines_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
