# Generated by Django 5.0 on 2023-12-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0008_alter_headlines_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='related_news',
            field=models.ManyToManyField(blank=True, to='timee.headlines'),
        ),
    ]
