# Generated by Django 5.0 on 2023-12-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0009_headlines_related_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlines',
            name='related_news',
            field=models.ManyToManyField(blank=True, related_name='related_by', to='timee.headlines'),
        ),
    ]
