# Generated by Django 5.0 on 2023-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0010_alter_headlines_related_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='headlines',
            name='other_sources',
            field=models.ManyToManyField(related_name='headlines', to='timee.source'),
        ),
    ]
