# Generated by Django 5.0 on 2024-01-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0011_source_headlines_other_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFetchTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
