# Generated by Django 5.0 on 2024-01-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0013_firme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firme',
            name='id_broj',
            field=models.IntegerField(default=None, max_length=100),
        ),
    ]
