# Generated by Django 5.0 on 2024-01-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0014_alter_firme_id_broj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firme',
            name='id_broj',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
