# Generated by Django 5.0 on 2024-01-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0015_alter_firme_id_broj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastfetchtime',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
