# Generated by Django 5.0 on 2024-01-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0016_alter_lastfetchtime_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastfetchtime',
            name='update_time',
        ),
        migrations.AddField(
            model_name='lastfetchtime',
            name='last_update_time',
            field=models.DateTimeField(default=None),
        ),
    ]
