# Generated by Django 5.0 on 2024-01-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0019_lastfetchtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastFetchTime',
            new_name='LastFetch',
        ),
    ]
