# Generated by Django 5.0 on 2024-01-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0013_headlines_source_name'),
        ('timee', '0022_lastfetch'),
    ]

    operations = [
    ]
