# Generated by Django 5.0 on 2024-01-14 15:08

import timee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timee', '0023_merge_0013_headlines_source_name_0022_lastfetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firme',
            name='sifra',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='image_urls',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
